### ISSUE TITLE
Label is not working

### ISSUE THREAD

**Issue by saumilsdk** [mcaule/d3-timeseries#10]
Specified legend label doesn't appear.

let chart1 = d3_timeseries()
            .addSerie(b1Items, {
                x: 'date',
                y: 'signalStrength',
            }, {interpolate: 'monotone', label:"B1 Signal Strength"})

**Comment by WillFleming** [comment]
@saumilsdk Is your data sorted by ascending date? I think unsorted data was causing this issue for me.

**Comment by saumilsdk** [comment]
Yes you are right as my data is descending order but that should not matter i suppose.

**Comment by saumilsdk** [comment]
Data has to be in sorted order
