### ISSUE TITLE
How to define #chart in the tutorials

### ISSUE THREAD

**Issue by zhaottcrystal** [mcaule/d3-timeseries#5]
Dear Author,
   In your first example shown  `

//data :
--
  | // [{date:new Date('2013-01-01'),n:120,n3:200},...]
  | var chart = d3.timeseries()
  | .addSerie(data,{x:'date',y:'n',diff:'n3'},{interpolate:'monotone',color:"#333"})
  | .width(900)
  |  
  | chart('#chart')

`
I am wondering how do you define "#chart" in your examples. I did not find it in your source code.
Thanks a lot for your help! Much appreciated!

Best,
Tingting

**Comment by mcaule** [comment]
`#chart` is a selector for a div defined in the html. You can pass a document node.
