### ISSUE TITLE
new version of d3 breaks the code

### ISSUE THREAD

**Issue by cup-of** [mcaule/d3-timeseries#6]
Hello, If i use a new version of d3, then things break. specifically in d3_timeseries.js, things like scale.linear dont work. could you update to work with the new version of d3?

**Comment by FarisCS** [comment]
Good link about migrating from D3v3 to D3v4:

https://github.com/d3/d3/blob/master/CHANGES.md

**Comment by LuciferSam86** [comment]
Is this project dead? Are there any alternatives? I would like to implement it on my project, but since I am using d3 v4, will it work?

**Comment by mcaule** [comment]
Hello, 

This project is now compatible with d3 v4 and npm. 

Thank you.
